### ISSUE TITLE
Windows image failed to build

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy-build-tools#104]
I think due to some flake when the last PR landed (#103) the windows toolchain doesnt seem to have been rebuilt.

this is blocking envoyproxy/envoy#13362 as that updates the (hash) tags on the images, and the windows image doesnt exist

**Comment by mattklein123** [comment]
cc @envoyproxy/windows-dev could you help with this?

**Comment by phlax** [comment]
my guess is that an empty commit to master will fix

**Comment by sunjayBhatia** [comment]
It looks like downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20200720.tar.xz is still failing

I can poke around and see if theres an alternative but if I remember from last week, all msys2 site downloads were acting up

**Comment by sunjayBhatia** [comment]
(Downloading from that link myself is also not working, getting an error via wget and the browser)

**Comment by phlax** [comment]
yep, not working for me - are there any alternatives ?

**Comment by phlax** [comment]
@sunjayBhatia i think this is a list of mirrors:

https://github.com/msys2/MSYS2-packages/blob/master/pacman-mirrors/mirrorlist.msys

**Comment by sunjayBhatia** [comment]
the main site says github/sourceforge downloads are good still: https://www.msys2.org/

we can switch the URL to a github URL and bump to the latest release: https://github.com/msys2/msys2-installer/releases/download/2020-09-03/msys2-base-x86_64-20200903.tar.xz via https://github.com/msys2/msys2-installer/releases

**Comment by phlax** [comment]
yep this works too:

**Comment by phlax** [comment]
just realised that its a `cn` mirror which is probs not optimal on network - but it was the first i tried from  the mirror list

**Comment by sunjayBhatia** [comment]
@phlax PR coming shortly to bump msys2

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy-build-tools/pull/105
