### ISSUE TITLE
Current build image fails with missing `'@envoy_build_tools//toolchains:configs/windows/versions.bzl'`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy-build-tools#147]
We are unable to update (the toolchains) in Envoy currently due to missing `versions.bzl` 

cc @yanavlasov @wrowe

**Comment by yanavlasov** [comment]
I'm actively working on this. If I'm unable to resolve this by EOD I will revert my changes.

**Comment by wrowe** [comment]
Just to assess this, the most recent build image generated from a4bc79 on windows does not have the required versions.bzl files in linux/ or windows/ trees.

The very latest build images from bb5c64 were not deposited to dockerhub according to

**Comment by wrowe** [comment]
Still have a WORKSPACE under envoy-build-tools doing this
```
WORKSPACE:load("//toolchains:rbe_toolchains_config.bzl", "rbe_toolchains_config")
```
which in turn attempts this;
```
./toolchains/rbe_toolchains_config.bzl:load("@envoy_build_tools//toolchains:configs/linux/versions.bzl", _generated_toolchain_config_suite_autogen_spec_linux = "TOOLCHAIN_CONFIG_AUTOGEN_SPEC")
./toolchains/rbe_toolchains_config.bzl:load("@envoy_build_tools//toolchains:configs/windows/versions.bzl", _generated_toolchain_config_suite_autogen_spec_windows = "TOOLCHAIN_CONFIG_AUTOGEN_SPEC")
```
and thus, blows up when that build image is used under envoy here;
```
bazel/dependency_imports.bzl:load("@envoy_build_tools//toolchains:rbe_toolchains_config.bzl", "rbe_toolchains_config")
```
It seems this needs fixing prior to adopting any new build container image. There's no immediate reason to back this out if we can address this problem on envoy-build-tools in the short term.

**Comment by yanavlasov** [comment]
Sorry, I'm not following I do not see this in the https://github.com/envoyproxy/envoy-build-tools/blob/main/WORKSPACE

**Comment by wrowe** [comment]
> Sorry, I'm not following I do not see this

You were right, it didn't exist there, that copy in my tree needed a git pull. Sorry for the confusion.

We still pulled in the wrong image in //envoyproxy/envoy/bazel/dependency_imports.bzl.

**Comment by phlax** [comment]
any eta for a resolution on this ?

currently, im blocked from landing the packaging code waiting for the build image to be updated

**Comment by phlax** [comment]
i believe this is now fixed
