### ISSUE TITLE
Install gcloud SDK in the build images

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy-build-tools#16]
It looks that when logged Docker is configured to use GCP credentials (i.e. `gcloud auth activate-service-account`, `gcloud auth configure-docker`), then Bazel needs `docker-credential-gcloud` from gcloud SDK to be available in `$PATH` in order to pull Docker images `container_pull`.

**Comment by PiotrSikora** [comment]
cc @lizan

**Comment by lizan** [comment]
This is actually on my wishlist as well. It reduces the need for another image for coverage_push etc. @PiotrSikora can you take this?
