### ISSUE TITLE
Windows build is failing with trust issues

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy-build-tools#160]
The windows build is consistently failing with the following:

```
error: perl-File-Listing: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust

```

and related errors.

there are some discussions about this:

- https://github.com/msys2/MSYS2-packages/issues/2343
- https://stackoverflow.com/questions/68669920/invalid-pgp-signature-when-updating-packages-in-msys2-despite-fixes/70088371#70088371

as this only started to happen in the last day or two its not clear if its transient or something changed and we need to clear some keys or somesuch

**Comment by wrowe** [comment]
This is typical of a new signatory to the package collection, and requires a bump in the base msys2 package provisioned in our build_windows_toolchain.ps1 script. Patch incoming.

**Comment by phlax** [comment]
closing as we dont officially support windows any longer
