### ISSUE TITLE
Build image cannot apt update

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy-build-tools#193]
Currently some of the keys that are fetched into the build image have expired 

This has led to failing in CI which we have worked around

Related ticket https://github.com/envoyproxy/envoy/issues/25069

**Comment by Pawan-Bishnoi** [comment]
any concerns with the build failures in the [merge commit](https://github.com/envoyproxy/envoy-build-tools/commit/7304f974de2724617b7492ccb4c9c58cd420353a) ?

```
#15 ERROR: failed to push gcr.io/envoy-ci/envoy-build:7304f974de2724617b7492ccb4c9c58cd420353a: failed to copy: io: read/write on closed pipe
------
 > exporting to image:
------
ERROR: failed to solve: failed to push gcr.io/envoy-ci/envoy-build:7304f974de2724617b7492ccb4c9c58cd420353a: failed to copy: io: read/write on closed pipe
##[error]Bash exited with code '1'.
Finishing: Bash

```

**Comment by phlax** [comment]
well, without it passing it wont produce the docker image/s

not sure what the issue is - this CI has always been a bit flakey - just kicked it again, 3rd time lucky hopefully

if it fails again we can investigate further - maybe its something to do with gcp key - seems to be the time of year for it
