### ISSUE TITLE
add pkg-config to build containers

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy-build-tools#303]
in https://github.com/envoyproxy/envoy/pull/29881 we have a dependency that the cmake requires the availability of pkg-config
can pkg-config be added to the build containers?
@htuch, @phlax, @lizan  is this the right place to log this issue?

**Comment by phlax** [comment]
@sambercovici generally we want to remove things from the container/host env rather than adding and push anything we can into the bazel layer

im wondering if there is a way we can do this with bazel - quick search turned up this https://github.com/cherrry/bazel_pkg_config altho doesnt seem to be actively maintained

**Comment by sambercovici** [comment]
Hi @phlax,
The [bazel package](https://github.com/cherrry/bazel_pkg_config) looks like a wrapper around a pre-installed pkg-config.
It allows to define dependencies in bazel that will be checked and loaded using pkg-config.
in https://github.com/envoyproxy/envoy/pull/29881 the vecorscan cmake needs pre installed pkg-config.
So, the ask to have it available in the build container.

**Comment by phlax** [comment]
> looks like a wrapper around a pre-installed pkg-config

yeah, probs doesnt help much

>  I had to patch the cmake to remove this dependency, but would like to stop needing such a patch.

not sure on best way forward - we want to keep host env requirements to absolute minimum so i think a patch is preferable to a dep if the dep is not actually required

**Comment by sambercovici** [comment]
pre installing pkg-config does not increase the host env requirements as AFAIK, all linux derivatives, macos and windows supports this.
@markos has stated in https://github.com/envoyproxy/envoy/pull/29881#issuecomment-1826273753 that they plan to maintain and extend the use of pkg-config. As a result, not having it will mean that each promotion of vectorscan to new versions may add additional patches to circumvent the lack of pkg-config.

**Comment by phlax** [comment]
> pre installing pkg-config does not increase the host env requirements 

obv it does if its a build requirement - not saying its not trivial to install - but just dont want to make users do it if its not strictly necessary

~relatedly it makes me think that there are parts of the vectorscan build that may not be required - we really want to minimize encumberance with extensions/deps and these cmake build so often build a lot of binaries unnecessarily

**Comment by phlax** [comment]
> ust dont want to make users do it if its not strictly necessary

also it breaks hermeticity - probs in no consequential way if its not used, but it means the build is not hermetic all the same

**Comment by sambercovici** [comment]
> > ust dont want to make users do it if its not strictly necessary
> 
> also it breaks hermeticity - probs in no consequential way if its not used, but it means the build is not hermetic all the same

I agree. 
I opened https://github.com/VectorCamp/vectorscan/issues/208 lets see how this proceeds.

**Comment by sambercovici** [comment]
@phlax 
should we leave this open or close and reopen if this is still needed after the next version of vectorscan?

**Comment by phlax** [comment]
up to you - i dont mind keeping it open to track the issue, but would rather it didnt land 8/

**Comment by sambercovici** [comment]
closing. will open new issue if needed.
