### ISSUE TITLE
devcontainer docker build is broken due to old apt key for kitware

### ISSUE THREAD

**Issue by erikjoh** [envoyproxy/envoy-build-tools#307]
Same issue as #163 .

Trying to use the devcontainer currently results in:

```
3.508 W: GPG error: https://apt.kitware.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
3.508 E: The repository 'https://apt.kitware.com/ubuntu focal InRelease' is not signed.
```

Because there's a new 2024 key that must be used instead.

Should be fixed by running a new build of this repo so that this line picks up the new 2024 key:

https://github.com/envoyproxy/envoy-build-tools/blob/157af2cabe71d054d4b9837a66f8458cb7bee2f0/docker/linux/ubuntu/Dockerfile#L82

To reproduce:

```
docker run -it --rm --entrypoint apt gcr.io/envoy-ci/envoy-build:fd9ec000fdd72d5c5e4e4ef16db4f9103058779e update
```

**Comment by phlax** [comment]
thanks for raising this @erikjoh - there are a number of recurring issues with the kitware repo

ill kick a new build of the container now

**Comment by erikjoh** [comment]
Thanks!

Noticed the new image `0ca52447572ee105a4730da5e76fe47c9c5a7c64` is already available and based on this it seems to be fixed now:

```
docker run -it --rm --entrypoint apt gcr.io/envoy-ci/envoy-build:0ca52447572ee105a4730da5e76fe47c9c5a7c64 update
...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

Guess a PR like this one https://github.com/envoyproxy/envoy/pull/19949/files is also needed for the Envoy repo but feel free to close this issue.

**Comment by phlax** [comment]
yeah - on it now
