### ISSUE TITLE
How to get envoy-build-tools commit hash that was used to build envoy-build-ubuntu docker image

### ISSUE THREAD

**Issue by shyaamsn** [envoyproxy/envoy-build-tools#43]
I am trying to build envoy from source and I would like to know which commit of envoy-build-tools was used to generate envoy-build-ubuntu docker image.

e.g. If I go to envoy repo and get the build sha (say 3788a87461f2b3dc8048ad0ce5df40438a56e0a8f1a4ab0f61b4ef0d8c11ff1f) how do i know which commit of envoy-build-tools was used to generate this  image?

I am trying to replicate the build process in my organization with the intent of build reproducibility and air-gapped builds (i.e. builds which dont need to go out to Internet to fetch dependencies). For this purpose, I would like to know this info so that whenever a new version of envoy is released, I can build envoy-build-ubuntu docker container internally (using the same commit of envoy-build-tools ) and use that to build envoy.

**Comment by sunjayBhatia** [comment]
you can look in this file: https://github.com/envoyproxy/envoy/blob/a539a048503484dcca6044587b50405aafb71bcc/bazel/repository_locations.bzl#L23-L28

**Comment by shyaamsn** [comment]
thanks @sunjayBhatia
